package io.github.achirdlabs.rift.model;

import io.github.achirdlabs.rift.json.JsonObject;
import io.github.achirdlabs.rift.json.JsonString;
import io.github.achirdlabs.rift.json.JsonValue;

import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.Set;

/**
 * A stub response. Exactly one of {@code is}/{@code proxy}/{@code inject}/{@code fault} is
 * present, or the response is generated entirely by a {@code _rift} script (no {@code is} block).
 * Priority when more than one is present, matching the engine: {@code is} &gt; {@code proxy} &gt;
 * {@code inject} &gt; {@code fault} &gt; script-only. A flat/recorded form (top-level
 * {@code statusCode}/{@code headers}/{@code body}/{@code _mode}, optionally with a {@code _rift}
 * extension) reads as an {@code is} response, normalized to the canonical {@code is:{}} shape. Any
 * other object — no known kind, no flat fields — also reads as an {@code is} response, preserving
 * its unknown keys via {@link IsResponse#extra} rather than dropping them. The {@code proxy}/{@code
 * inject}/{@code fault}/script-only kinds — and the wrapped {@code is} form — each carry an {@code
 * extra} escape hatch for co-present sibling top-level keys, so no kind silently drops data.
 */
public sealed interface Response {

    /**
     * A literal ("is") response. {@code extra} carries any top-level wire keys that sat alongside a
     * <em>wrapped</em> {@code is:{}} (e.g. an unknown/future key, or a {@code proxy:null} migration-compat
     * sibling) so they survive a parse → serialize round-trip instead of being dropped. The typed
     * siblings ({@code _behaviors}/{@code behaviors}/{@code _rift}) and {@code is} itself are never in
     * {@code extra}. The flat/recorded form keeps its unknowns inside {@link IsResponse#extra} instead.
     */
    record Is(IsResponse is, Behaviors behaviors, Optional<RiftResponseExtension> rift,
            Map<String, JsonValue> extra) implements Response {
        public Is {
            Objects.requireNonNull(is, "is");
            Objects.requireNonNull(behaviors, "behaviors");
            Objects.requireNonNull(rift, "rift");
            Objects.requireNonNull(extra, "extra");
            JsonSupport.rejectModeledExtraKeys(extra, Set.of("is", "_behaviors", "behaviors", "_rift"), "is response");
            extra = JsonSupport.orderedCopy(extra);
        }

        public Is(IsResponse is, Behaviors behaviors, Optional<RiftResponseExtension> rift) {
            this(is, behaviors, rift, Map.of());
        }
    }

    /**
     * A proxy response. {@code extra} carries any top-level wire keys that sat alongside {@code proxy}
     * (e.g. {@code _behaviors} or unknown/future keys) so they survive a parse → serialize round-trip
     * instead of being dropped — {@code proxy} itself is never in {@code extra}.
     */
    record Proxy(ProxyResponse proxy, Map<String, JsonValue> extra) implements Response {
        public Proxy {
            Objects.requireNonNull(proxy, "proxy");
            Objects.requireNonNull(extra, "extra");
            JsonSupport.rejectModeledExtraKeys(extra, Set.of("proxy"), "proxy response");
            extra = JsonSupport.orderedCopy(extra);
        }

        public Proxy(ProxyResponse proxy) {
            this(proxy, Map.of());
        }
    }

    /** An inject (script) response. {@code extra} preserves sibling top-level keys (see {@link Proxy}). */
    record Inject(String script, Map<String, JsonValue> extra) implements Response {
        public Inject {
            Objects.requireNonNull(script, "script");
            Objects.requireNonNull(extra, "extra");
            JsonSupport.rejectModeledExtraKeys(extra, Set.of("inject"), "inject response");
            extra = JsonSupport.orderedCopy(extra);
        }

        public Inject(String script) {
            this(script, Map.of());
        }
    }

    /** A raw-fault response. {@code extra} preserves sibling top-level keys (see {@link Proxy}). */
    record Fault(String fault, Map<String, JsonValue> extra) implements Response {
        public Fault {
            Objects.requireNonNull(fault, "fault");
            Objects.requireNonNull(extra, "extra");
            JsonSupport.rejectModeledExtraKeys(extra, Set.of("fault"), "fault response");
            extra = JsonSupport.orderedCopy(extra);
        }

        public Fault(String fault) {
            this(fault, Map.of());
        }
    }

    /**
     * Rift script-only response: no {@code is} block, the response is generated by the script.
     * {@code extra} carries any top-level wire keys that sat alongside {@code _rift} (e.g.
     * {@code _behaviors} or unknown/future keys) so they survive a parse → serialize round-trip
     * instead of being dropped — {@code _rift} itself is never in {@code extra}.
     */
    record RiftScript(RiftResponseExtension rift, Map<String, JsonValue> extra) implements Response {
        public RiftScript {
            Objects.requireNonNull(rift, "rift");
            Objects.requireNonNull(extra, "extra");
            JsonSupport.rejectModeledExtraKeys(extra, Set.of("_rift"), "rift script");
            extra = JsonSupport.orderedCopy(extra);
        }

        public RiftScript(RiftResponseExtension rift) {
            this(rift, Map.of());
        }
    }

    static Response read(JsonObject obj) {
        if (obj.get("is") != null) {
            return new Is(
                    IsResponse.read(JsonSupport.requireObject(obj.get("is"), "is")),
                    readBehaviors(obj),
                    readRift(obj),
                    JsonSupport.extraFields(obj, Set.of("is", "_behaviors", "behaviors", "_rift")));
        }
        if (obj.get("proxy") != null) {
            return new Proxy(
                    ProxyResponse.read(JsonSupport.requireObject(obj.get("proxy"), "proxy")),
                    JsonSupport.extraFields(obj, Set.of("proxy")));
        }
        if (obj.get("inject") != null) {
            return new Inject(JsonSupport.requireString(obj, "inject"), JsonSupport.extraFields(obj, Set.of("inject")));
        }
        if (obj.get("fault") != null) {
            return new Fault(JsonSupport.requireString(obj, "fault"), JsonSupport.extraFields(obj, Set.of("fault")));
        }
        boolean hasFlatIsFields = obj.has("statusCode") || obj.has("headers") || obj.has("body") || obj.has("_mode");
        // A script-only response is "no is block" (per this interface's contract): a bare _rift with
        // no flat is-fields. A _rift ALONGSIDE flat is-fields is the flat equivalent of the wrapped
        // {is:{}, _rift:{}} form, so it falls through to the Is branch below (which keeps both) rather
        // than being read as script-only, which would drop the is-fields.
        if (obj.get("_rift") != null && !hasFlatIsFields) {
            return new RiftScript(
                    RiftResponseExtension.read(JsonSupport.requireObject(obj.get("_rift"), "_rift")),
                    JsonSupport.extraFields(obj, Set.of("_rift")));
        }
        // Flat/recorded form: a bare "is" response with no wrapper — top-level statusCode/headers/
        // body/_mode, as recorded stubs look. Read it as an Is (never lose the fields); it writes
        // back in the canonical is:{} shape. Behaviors and _rift are response-level siblings, so they
        // are read separately and stripped from the is-content; any genuinely unknown is-key is still
        // preserved through IsResponse.extra. An object naming no known kind and no flat fields lands
        // here too, so its unknown keys are preserved via IsResponse.extra rather than dropped.
        Behaviors behaviors = readBehaviors(obj);
        JsonObject isContent = JsonSupport.withoutKeys(obj, "_behaviors", "behaviors", "_rift");
        return new Is(IsResponse.read(isContent), behaviors, readRift(obj));
    }

    /**
     * Reads behaviors from either shape: the {@code _behaviors} object every fixture uses, or the
     * {@code behaviors} array-of-single-key-objects the engine itself emits in {@code GET /imposters}
     * output. Accepting the array form keeps consuming engine output from silently dropping them.
     */
    private static Behaviors readBehaviors(JsonObject obj) {
        JsonValue underscore = obj.get("_behaviors");
        if (underscore != null) {
            return Behaviors.read(JsonSupport.requireObject(underscore, "_behaviors"));
        }
        JsonValue array = obj.get("behaviors");
        if (array != null) {
            return Behaviors.readArray(JsonSupport.requireArray(array, "behaviors"));
        }
        return Behaviors.EMPTY;
    }

    private static Optional<RiftResponseExtension> readRift(JsonObject obj) {
        JsonValue rift = obj.get("_rift");
        return Optional.ofNullable(rift).map(v -> RiftResponseExtension.read(JsonSupport.requireObject(v, "_rift")));
    }

    /**
     * Writes this response. Uses an {@code instanceof} chain rather than a pattern-matching
     * {@code switch}: the latter is still a preview feature at the Java 17 release level this
     * module compiles against (finalized only in Java 21).
     */
    default JsonObject toJsonValue() {
        JsonObject.Builder builder = JsonObject.builder();
        if (this instanceof Is is) {
            builder.put("is", is.is().toJsonValue());
            if (!is.behaviors().isEmpty()) {
                builder.put("_behaviors", is.behaviors().toJsonValue());
            }
            is.rift().ifPresent(v -> builder.put("_rift", v.toJsonValue()));
            is.extra().forEach(builder::put);
        } else if (this instanceof Proxy proxy) {
            builder.put("proxy", proxy.proxy().toJsonValue());
            proxy.extra().forEach(builder::put);
        } else if (this instanceof Inject inject) {
            builder.put("inject", new JsonString(inject.script()));
            inject.extra().forEach(builder::put);
        } else if (this instanceof Fault fault) {
            builder.put("fault", new JsonString(fault.fault()));
            fault.extra().forEach(builder::put);
        } else if (this instanceof RiftScript riftScript) {
            builder.put("_rift", riftScript.rift().toJsonValue());
            riftScript.extra().forEach(builder::put);
        } else {
            throw new IllegalStateException("unreachable: " + this);
        }
        return builder.build();
    }
}
