package io.github.achirdlabs.rift.dsl;

import io.github.achirdlabs.rift.model.Behavior;
import io.github.achirdlabs.rift.model.Behaviors;
import io.github.achirdlabs.rift.model.Response;
import io.github.achirdlabs.rift.model.RiftResponseExtension;

import java.util.List;
import java.util.Map;
import java.util.Optional;

/**
 * A response entirely generated by a {@code _rift} script, with no {@code is} block — produced by
 * {@link RiftDsl#script(Script)}. Of the behaviors, the engine runs only {@code repeat} on it, so
 * {@link #repeat(int)} is its one chain method.
 */
public final class ScriptSpec implements ResponseSpec {

    private final Script script;
    private final Behaviors behaviors;

    private ScriptSpec(Script script, Behaviors behaviors) {
        this.script = script;
        this.behaviors = behaviors;
    }

    static ScriptSpec of(Script script) {
        return new ScriptSpec(script, Behaviors.EMPTY);
    }

    /**
     * Serves this response for the next {@code count} matches before the stub moves to its next
     * response, as {@link BehaviorChain#repeat} does on other responses (the block spelling, {@code
     * "_behaviors": {"repeat": n}}). It needs a following response to move to: on a stub's only
     * response it changes nothing. Requires a rift engine &ge; 0.18.0, which honours {@code repeat}
     * on every response; on {@code create} and {@code replaceAll} the SDK refuses to send it to an
     * older engine, which drops it silently. Calling it again replaces the count.
     */
    public ScriptSpec repeat(int count) {
        return new ScriptSpec(script, new Behaviors(List.of(new Behavior.Repeat(count))));
    }

    @Override
    public Response build() {
        RiftResponseExtension extension = new RiftResponseExtension(Optional.empty(), Optional.of(script.toConfig()), false);
        return new Response.RiftScript(extension, behaviors, Map.of());
    }
}
